# https://github.com/helix-editor/helix/blob/master/runtime/themes/base16_transparent.toml
inherits = "base16_transparent"

"ui.background" = { fg = "light-gray" }
"ui.linenr" = "gray"
"ui.virtual.ruler" = { bg = "#303030" }

"variable" = "white"
"constant" = "light-yellow"
"constant.numeric" = "yellow"
"type" = "yellow"
"namespace" = "magenta"
"comment" = "#90a840"
