theme = "custom"

[editor]
line-number = "relative"
bufferline = "multiple"
middle-click-paste = false
rulers = [80]
color-modes = true
auto-pairs = false
scrolloff = 8

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false
# git-ignore = false
# max-depth = 7

[keys.normal]
h = "no_op"

j = "move_char_left"
";" = "move_char_right"
k = "move_visual_line_up"
l = "move_visual_line_down"

V = ["select_mode", "extend_to_line_bounds"]
esc = ["collapse_selection", "keep_primary_selection"]

g = { a = "code_action" }
G = "goto_last_line"

"C-k" = ["goto_prev_paragraph", "move_visual_line_up", "collapse_selection"]
"C-l" = ["goto_next_paragraph", "collapse_selection"]
K = ["goto_prev_paragraph", "extend_line_up"]
L = ["goto_next_paragraph"]

J = "move_prev_word_start"
":" = "move_next_word_end"

"C-up" = ["page_up", "align_view_center"]
"C-down" = ["page_down", "align_view_center"]

D = "kill_to_line_end"
C = ["kill_to_line_end", "insert_mode"]

[keys.normal.space]
"/" = "toggle_comments"
"w" = ":write"
"W" = ":write-all"
"q" = ":quit"
"Q" = ":quit-all"
"j" = "goto_previous_buffer"
"left" = "goto_previous_buffer"
";" = "goto_next_buffer"
"right" = "goto_next_buffer"
"c" = ":buffer-close"

":" = "command_mode"

[keys.select]
h = "no_op"

j = "extend_char_left"
";" = "extend_char_right"
k = "extend_line_up"
l = "extend_line_down"

esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

g = { a = "code_action" }
G = "goto_last_line"

"C-k" = ["goto_prev_paragraph", "extend_line_up"]
"C-l" = ["goto_next_paragraph"]
"C-up" = ["page_up", "align_view_center"]
"C-down" = ["page_down", "align_view_center"]
D = "kill_to_line_end"
C = ["kill_to_line_end", "insert_mode"]


[keys.select.space]
"/" = "toggle_comments"
"w" = ":write"
"W" = ":write-all"
"q" = ":quit"
"Q" = ":quit-all"
"j" = "goto_previous_buffer"
"left" = "goto_previous_buffer"
";" = "goto_next_buffer"
"right" = "goto_next_buffer"
"c" = ":buffer-close"


